global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    labels:
      app: 'modular-mind'
      component: 'api'

  - job_name: 'embedding-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['embedding-service:8001']
    labels:
      app: 'modular-mind'
      component: 'embeddings'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    labels:
      app: 'modular-mind'
      component: 'system'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    labels:
      app: 'modular-mind'
      component: 'monitoring'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert_rules.yml'